# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69664a7170c0879733e0b0daf442a58af360263ee9ad07500180ce74daa7c416a1cded680b84c94a2d1deda45d8ac7f488fe83df5014f6b17692e5054dfecb1e

test:
  secret_key_base: efda4356b3907297c4bad29de6c3a6847edd9ae2632c2a4dae9e5c3c35cfa389e02b58aa1997972976cfcc382a4202abf28411ae33d1842dc01804a70037fa14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
